### ISSUE TITLE
Homework1

### ISSUE THREAD

**Issue by friosavila** [xcnecon/homework_1#1]
Couple of issues
1) reference.bib is not in the repository
2) neither its the figure image. 
If I try (or you try) to render this it will give you an error because those are missing

**Comment by xcnecon** [comment]
Hi Fernando. Thanks for letting me know. I didn't expect it to be run but definitely I should include them in the repository. They are uploaded now.

**Comment by friosavila** [comment]
Thank you. And no problem. That is why we have "code" reviewers to show this.
And you will know how to do this next time.
Good night
